# Generated by Django 5.0.6 on 2024-05-21 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_bio_alter_customuser_headline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='industry_iterests',
        ),
        migrations.RemoveField(
            model_name='organization_details',
            name='industry',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
    ]
