# Generated by Django 5.0.6 on 2024-05-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_remove_question_tags_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='votes',
        ),
        migrations.AddField(
            model_name='response',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
