# Generated by Django 5.0.6 on 2024-05-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_grouparticle_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouparticle',
            name='type',
            field=models.CharField(choices=[('lessons_learned', 'Lessons Learned'), ('best_practices', 'Best Practices'), ('other', 'Other')], default='Lessons Learned', max_length=20),
            preserve_default=False,
        ),
    ]
