# Generated by Django 5.0.6 on 2024-05-27 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_grouparticle_description_alter_grouparticle_authors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouparticle',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='coauthored_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
